### ISSUE TITLE
error: no such package

### ISSUE THREAD

**Issue by bartonhammond** [anticoders/meteor-helpers#1]
meteor add anti:helpers
 => Errors while parsing arguments:           

While adding package anti:helpers:
error: no such package

**Comment by apendua** [comment]
Ha! Good point. I haven't published it to atmosphere yet. Lemme fix it ...

**Comment by apendua** [comment]
Here it is:

https://atmospherejs.com/anti/helpers

Sorry for that. It was supposed to be an experimental package and I was planning to publish it some day. I wouldn't expect anyone to find it just hanging around on `github` :)
